[tool.poetry]
name = "poppy"
version = "0.1.0"
description = ""
authors = ["Varun Krishna S <varunhawk19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.93.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
